FROM node:18-alpine AS builder

WORKDIR /frontend

COPY package.json .
RUN npm i

COPY . .

RUN npm run build
# CMD [ "npm", "run", "build" ]

# COPY --from=builder /frontend/dist /usr/share/nginx/html