# Generated by Django 4.2.7 on 2024-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_created_at_ticket_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Высокий'), (2, 'Средний'), (3, 'Низкий')], default=3),
        ),
    ]
