# Generated by Django 4.2.7 on 2024-03-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_deadline_ticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Высокий'), (3, 'Низкий'), (2, 'Средний')], default=3),
        ),
    ]
