# Generated by Django 4.2.7 on 2024-03-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_is_active_alter_ticket_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(2, 'Средний'), (1, 'Высокий'), (3, 'Низкий')], default=3),
        ),
    ]
